version: '3.8'

services:
  web:
    build: .
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  redis:
    image: redis:alpine
    container_name: redis_cache
    ports: 
      - "6379:6379"
